---
abstract: 'Atom feed for web'
author:
  - 'Gea-Suan Lin <gslin@gslin.org>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Web-Atom
requires:
  Any::Moose: 0
  Carp: 0
  Encode: 0
  LWP::UserAgent: 0
  XML::Atom::Entry: 0
  XML::Atom::Feed: 0
  XML::Atom::Link: 0
  XML::Atom::Person: 0
  namespace::autoclean: 0
resources:
  homepage: https://github.com/gslin/web-atom-perl
  repository: https://github.com/gslin/web-atom-perl.git
version: 0.1.0
